name: any-pr

on: [pull_request]

jobs:
  build_test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
      - uses: mattrinternal/sre-reusable-action/actions/checkout@master
      - name: Build and test
        uses: mattrinternal/sre-reusable-action/actions/setup-node@master
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test --coverage
