## This workflow file is a WIP for the https://mattrglobal.atlassian.net/browse/DVP-11784 work where im looking at moving us off NPMJS, this is only to be used as a manual dispatch for now whilst testing

name: cd-libraries-gh

on:
  workflow_dispatch:

jobs:
  release-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Setup nodejs for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@mattrglobal"

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name.split('/')[1]")
          npm pkg set version="$(node -p "require('./package.json').version")-ghp-pilot.${{ github.run_number }}"
          npm publish --tag ghp-pilot
