name: Mirror repository to S3
on:
  push:
    branches:
      - master
jobs:
  BackupRepoToS3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # ping@v5.0.0
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::817632051851:role/oidc-github-actions-mattrglobal-global
          role-duration-seconds: 900
          role-session-name: GithubActions

      - name: Backing up this repo to AWS S3
        uses: peter-evans/s3-backup@59efd330705d92805a44894668b6cf5c10dc740e # pin@v1.1.1
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          MIRROR_TARGET: mattrglobal-github-backup/http-signatures
          SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        with:
          args: --overwrite --remove
