name: push-release

on:
  push:
    branches:
      - master

jobs:
  build_test_publish:
    name: Build, test, and publish release
    if: "contains(github.event.head_commit.message, 'chore(release): publish')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc 2> /dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
      - run: git config user.name "Mattr CI"
      - run: git config user.email "npmjs_ci_mattr_public@mattr.global"
      - run: yarn publish:stable
